language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/beastier
  - richelbilderbeek/beautier
  - richelbilderbeek/mauricer
  - richelbilderbeek/tracerer
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling

before_script:
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - Rscript -e "beastier::install_beast2()"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint
  # markdown-link-check, temporarily disabled due to CERT_UNTRUSTED
  #- sudo apt-get install npm
  #- sudo npm install -g markdown-link-check

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  - cd scripts; ./build_cran
  #- travis_wait 30 Rscript -e 'goodpractice::gp()'
  # temporarily disabled due to CERT_UNTRUSTED
  #- ./scripts/check_dead_links

after_failure:
  # - sudo Rscript install_this_r_package.R
  # - Rscript -e 'library(beautier); testit::assert(has_beast2())'
  - cat /home/travis/build/richelbilderbeek/beautier/..Rcheck/00install.out
  - cat /home/travis/build/richelbilderbeek/beautier/..Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
  - cat /home/travis/build/richelbilderbeek/beautier/..Rcheck/tests/testthat/testthat.log
