language: r
cache: packages

os: 
  - osx
  - linux

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - ropensci/beastier
  - ropensci/beautier
  - ropensci/mauricer
  - ropensci/tracerer
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling

before_script:
  - # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  - Rscript -e "beastier::install_beast2()"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint
  # markdown-link-check, temporarily disabled due to CERT_UNTRUSTED
  #- sudo apt-get install npm
  #- sudo npm install -g markdown-link-check

script:
  - travis_wait 30 R CMD build .
  - travis_wait 40 R CMD check *tar.gz

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'lintr::lint_package()'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'covr::codecov()'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes"; fi
  - # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi; fi
  # Do a CRAN build. No time :-(
  #- cd scripts; ./build_cran
  #- travis_wait 30 Rscript -e 'goodpractice::gp()'
  # temporarily disabled due to CERT_UNTRUSTED
  #- ./scripts/check_dead_links

after_failure:
  # - sudo Rscript install_this_r_package.R
  # - Rscript -e 'library(beautier); testit::assert(has_beast2())'
  - cat /home/travis/build/ropensci/beautier/..Rcheck/00install.out
  - cat /home/travis/build/ropensci/beautier/..Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
  - cat /home/travis/build/ropensci/beautier/..Rcheck/tests/testthat/testthat.log
